language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
deploy:
  provider: npm
  email: jp+spotifybot@spotify.com
  api_key:
    secure: qSrCaP2uzqRKaubBv8OaJQTG+4olKwAz1d0pcwyEFN2LXZx0t+n9hPaGIRL60xg748zu/bW+QULfUipeaI2JDci2XpcFjrKk58k6uaQK4Ed1hzNpxcwTiaUMm17Pk7f7cQ6abjXeiIYA0FXVAONFuDlZXHow3FmAqM9Or6kitYE=
  on:
    tags: true
